export const SESSION_SECRET = process.env.SESSION_SECRET || 'AeBacj@#1481!!'

export const envs = ["MYSQL_ROOT_PASSWORD",
  "MYSQL_DATABASE",
  "MYSQL_DATABASE_SHADOW",
  "MYSQL_USER",
  "MYSQL_PASSWORD",
  "INITIAL_ADMIN_USER",
  "INITIAL_ADMIN_PASSWORD"]
